# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  basics:
    runs-on: mini-elias
    container:
      imgae: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  try-checkers: # Run the complete throughput test with each checker
    container:
      image: python:3.12-slim
    needs: basics
    strategy:
      matrix:
        checker: [FileCheckerMixin]
    runs-on: mini-elias
    env:
      config_path: "placeholder/path"
    steps:
    - name: Assemble a parser config for this checker
      run: python tests/make_config.py checker {{ matrix.checker }}
    - name: Prepare an individual source parser
      run: python prepare.py $config_path
    - name: Run the trial parser
      run: python run.py $config_path
